version: '3.9'
services:
  geoipupdate:
    container_name: geoipupdate
    image: ghcr.io/maxmind/geoipupdate
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=$GEOIPUPDATE_ACCOUNT_ID
      - GEOIPUPDATE_LICENSE_KEY=$GEOIPUPDATE_LICENSE_KEY
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country'
      - GEOIPUPDATE_FREQUENCY=72
    networks:
      - geoipupdate
    volumes:
      - 'geoipupdate_data:/usr/share/GeoIP'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $PORTRAW:$PORTRAW
    environment:
      - DB_LOCATION=$DB_LOCATION
      - PORT=$PORT
    depends_on:
      - geoipupdate
    networks:
      - geoipupdate
    volumes:
      - 'geoipupdate_data:/usr/share/GeoIP'
    restart: always

networks:
  geoipupdate:

volumes:
  geoipupdate_data:
    driver: local
